name: Main

on:
  workflow_dispatch:
  pull_request:
    branches: main
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "tests/**"
      - "Dockerfile"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "tests/**"
      - "Dockerfile"

jobs:

  checks:
    uses: ./.github/workflows/checks.yml

  tests:
    needs:
      - checks
    uses: ./.github/workflows/tests.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  release-docker:
    needs:
      - tests
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    uses: ./.github/workflows/release-docker.yml
    with:
      push: true
    secrets:
      nexus_username: ${{ secrets.NEXUS_USERNAME }}
      nexus_token: ${{ secrets.NEXUS_TOKEN }}

  security-checks:
    needs:
      - tests
      - release-docker
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    uses: ./.github/workflows/security-checks.yml
    with:
      version: main
    secrets:
      security_checks_token: ${{ secrets.SYSDIG_CHECK_TRIGGER }}