name: Tag CI

on:
  push:
    tags:
      - "v*"

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  release-docker:
    needs:
      - tests
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    uses: ./.github/workflows/release-docker.yml
    with:
      push: true
    secrets:
      nexus_username: ${{ secrets.NEXUS_USERNAME }}
      nexus_token: ${{ secrets.NEXUS_TOKEN }}